autoreleasefool/approach

app/src/main/java/ca/josephroque/bowlingcompanion/Constants.java, app/src/main/java/ca/josephroque/bowlingcompanion/fragment/GameFragment.java, app/src/main/res/values/strings_activity_settings.xml, app/src/main/res/xml/pref_game.xml
=> Automatically lock games after a 5 second delay

app/src/main/java/ca/josephroque/bowlingcompanion/MainActivity.java, app/src/main/java/ca/josephroque/bowlingcompanion/adapter/SeriesAdapter.java, app/src/main/java/ca/josephroque/bowlingcompanion/fragment/GameFragment.java, app/src/main/java/ca/josephroque/bowlingcompanion/fragment/SeriesFragment.java, app/src/main/res/layout/list_item_series.xml, app/src/main/res/menu/menu_game.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
=> Move series stats to list item, move edit series to long press

app/src/main/java/ca/josephroque/bowlingcompanion/MainActivity.java
=> Only start thread if it is new, otherwise report error and skip it

app/src/main/java/ca/josephroque/bowlingcompanion/Constants.java, app/src/main/res/values/strings_activity_settings.xml, app/src/main/res/xml/pref_game.xml
=> Change Sp toHS, Hp to HP as per C5PBA Regulations

app/src/main/java/ca/josephroque/bowlingcompanion/fragment/SeriesFragment.java
=> Don't prompt series combine if series is at max

app/src/main/java/ca/josephroque/bowlingcompanion/MainActivity.java, app/src/main/java/ca/josephroque/bowlingcompanion/fragment/GameFragment.java
=> Use bowler name as GameFragment title

ios/Approach/Sources/AlleysRepository/AlleysRepository+Live.swift, ios/Approach/Sources/DatabaseModelsLibrary/Lane+Database.swift, ios/Approach/Sources/LanesRepository/LanesRepository+Live.swift, ios/Approach/Tests/AlleysRepositoryTests/AlleysRepositoryTests.swift, ios/Approach/Tests/GamesRepositoryTests/GamesRepositoryTests.swift, ios/Approach/Tests/LanesRepositoryTests/LanesRepositoryTests.swift
=> Fix: Order lanes correctly by label alphanumerically

ios/Approach/Package.swift, ios/Approach/Package.swift.toml, ios/Approach/Sources/DatabaseLibrary/Migrations/DBMigration.swift, ios/Approach/Sources/DatabaseLibrary/Migrations/Migration20230920ValidateGameScores.swift, ios/Approach/Tests/DatabaseLibraryTests/DBMigrationTests.swift
=> Fix: Recalculate game scores from frames to resolve sync errors

ios/Approach/Sources/ScoreKeeperModelsLibrary/Pin.swift, ios/Approach/Sources/StatisticsLibrary/Statistics.swift, ios/Approach/Sources/StatisticsLibrary/Trackable/FirstRoll/Statistics+Fives.swift, ios/Approach/Sources/StatisticsLibrary/Trackable/FirstRoll/Statistics+FivesSpared.swift, ios/Approach/Sources/StatisticsLibrary/Trackable/FirstRoll/Statistics+LeftFives.swift, ios/Approach/Sources/StatisticsLibrary/Trackable/FirstRoll/Statistics+LeftFivesSpared.swift, ios/Approach/Sources/StatisticsLibrary/Trackable/FirstRoll/Statistics+RightFives.swift, ios/Approach/Sources/StatisticsLibrary/Trackable/FirstRoll/Statistics+RightFivesSpared.swift, ios/Approach/Sources/StringsLibrary/Strings+Generated.swift, ios/Approach/Sources/StringsLibrary/en.lproj/Localizable.strings, ios/Approach/Tests/StatisticsLibraryTests/Trackable/FirstRoll/Statistics+FivesSparedTests.swift, ios/Approach/Tests/StatisticsLibraryTests/Trackable/FirstRoll/Statistics+FivesTests.swift, ios/Approach/Tests/StatisticsLibraryTests/Trackable/FirstRoll/Statistics+LeftFivesSparedTests.swift, ios/Approach/Tests/StatisticsLibraryTests/Trackable/FirstRoll/Statistics+LeftFivesTests.swift, ios/Approach/Tests/StatisticsLibraryTests/Trackable/FirstRoll/Statistics+RightFivesSparedTests.swift, ios/Approach/Tests/StatisticsLibraryTests/Trackable/FirstRoll/Statistics+RightFivesTests.swift
Fixes #302 
Introduces 5 new statistics: Fives, Fives Spared, Left Fives, Left Fives Spared, Right Fives, and Right Fives Spared
=> Feat: Fives statistic

android/.gitignore, android/app/build.gradle.kts, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/ca/josephroque/bowlingcompanion/MainActivity.kt, android/app/src/main/java/ca/josephroque/bowlingcompanion/MainActivityViewModel.kt, android/app/src/main/java/ca/josephroque/bowlingcompanion/core/analytics/AnalyticsClient.kt, android/app/src/main/java/ca/josephroque/bowlingcompanion/core/analytics/TelemetryDeckAnalyticsClient.kt, android/app/src/main/java/ca/josephroque/bowlingcompanion/core/analytics/TrackableEvent.kt, android/app/src/main/java/ca/josephroque/bowlingcompanion/core/analytics/di/AnalyticsModule.kt, android/app/src/main/java/ca/josephroque/bowlingcompanion/core/data/repository/OfflineFirstUserDataRepository.kt, android/app/src/main/java/ca/josephroque/bowlingcompanion/core/data/repository/UserDataRepository.kt, android/app/src/main/java/ca/josephroque/bowlingcompanion/core/datastore/ApproachPreferencesDataSource.kt, android/app/src/main/java/ca/josephroque/bowlingcompanion/core/model/UserData.kt, android/app/src/main/proto/ca/josephroque/bowlingcompanion/core/data/analytics_opt_in.proto, android/app/src/main/proto/ca/josephroque/bowlingcompanion/core/data/user_preferences.proto, android/build.gradle.kts, android/settings.gradle.kts
Part of #339 
Introduces `AnalyticsClient` and `TelemetryDeckAnalyticsClient` implementation, initialize the client with the AppID on launch.
=> Feat: Setup TelemetryDeck analytics

ios/Approach.xcodeproj/project.pbxproj, ios/Approach.xcodeproj/xcshareddata/xcschemes/AppInfoServiceTests.xcscheme, ios/Approach.xcodeproj/xcshareddata/xcschemes/StoreReviewServiceTests.xcscheme, ios/Approach/Package.swift, ios/Approach/Package.swift.toml, ios/Approach/Sources/AppFeature/App.swift, ios/Approach/Sources/AppInfoService/AppInfoService+Live.swift, ios/Approach/Sources/AppInfoServiceInterface/AppInfoService+Interface.swift, ios/Approach/Sources/GamesEditorFeature/GamesEditor+GameDetails.swift, ios/Approach/Sources/GamesEditorFeature/GamesEditor.swift, ios/Approach/Sources/GamesEditorFeature/GamesEditorView.swift, ios/Approach/Sources/PreferenceServiceInterface/PreferenceKey.swift, ios/Approach/Sources/StoreReviewService/StoreReviewService+Live.swift, ios/Approach/Sources/StoreReviewServiceInterface/StoreReviewService+Interface.swift, ios/Approach/Tests/AppInfoServiceTests/AppInfoServiceTests.swift, ios/Approach/Tests/StoreReviewServiceTests/StoreReviewServiceTests.swift
Fixes #318 
Prompts user for reviews when conditions are met:
- Installed > 7 days ago
- Last requested a review > 7 days ago
- Has opened the app at least 3 times
- Has not been asked for a review of this version yet
The prompt is presented after a user successfully finishes recording a game for now.
=> Request App Store reviews on iOS

ios/Approach/Sources/DatabaseLibrary/Migrations/DBMigration.swift, ios/Approach/Sources/DatabaseLibrary/Migrations/Migration20231128AddDurationToGame.swift, ios/Approach/Sources/DatabaseModelsLibrary/Game+Database.swift, ios/Approach/Sources/DatabaseModelsLibrary/Series+Database.swift, ios/Approach/Sources/GamesEditorFeature/GamesEditor+Effects.swift, ios/Approach/Sources/GamesEditorFeature/GamesEditor+GameDetails.swift, ios/Approach/Sources/GamesEditorFeature/GamesEditor.swift, ios/Approach/Sources/GamesRepositoryInterface/Models/Game+Edit.swift, ios/Approach/Sources/TestDatabaseUtilitiesLibrary/DatabaseGenerator.swift, ios/Approach/Sources/TestDatabaseUtilitiesLibrary/Models/Games+DatabaseUtilities.swift, ios/Approach/Tests/DatabaseLibraryTests/DBMigrationTests.swift, ios/Approach/Tests/GamesRepositoryTests/GamesRepositoryTests.swift
=> Track game duration

ios/Approach.xcodeproj/project.pbxproj, ios/Approach/Package.swift, ios/Approach/Package.swift.toml, ios/Approach/Sources/AppFeature/App.swift, ios/Approach/Sources/LaunchService/LaunchService+Live.swift, ios/Approach/Sources/LaunchServiceInterface/LaunchService+Interface.swift, ios/Approach/Tests/LaunchServiceTests/File.swift, ios/ApproachIOS/Source/ApproachApp.swift
=> feat(ios): move launch logic to LaunchService

android/app/build.gradle.kts, android/app/src/main/AndroidManifest.xml, android/gradle/libs.versions.toml
=> feat(android): integrate sentry

android/feature/accessoriesoverview/src/main/java/ca/josephroque/bowlingcompanion/feature/accessoriesoverview/AccessoriesViewModel.kt, android/feature/alleyform/src/main/java/ca/josephroque/bowlingcompanion/feature/alleyform/AlleyFormScreenUi.kt, android/feature/alleyform/src/main/java/ca/josephroque/bowlingcompanion/feature/alleyform/AlleyFormViewModel.kt, android/feature/avatarform/src/main/java/ca/josephroque/bowlingcompanion/feature/avatarform/AvatarFormScreenUi.kt, android/feature/avatarform/src/main/java/ca/josephroque/bowlingcompanion/feature/avatarform/AvatarFormViewModel.kt, android/feature/bowlerform/src/main/java/ca/josephroque/bowlingcompanion/feature/bowlerform/BowlerFormScreenUi.kt, android/feature/bowlerform/src/main/java/ca/josephroque/bowlingcompanion/feature/bowlerform/BowlerFormViewModel.kt, android/feature/gameseditor/ui/src/main/java/ca/josephroque/bowlingcompanion/feature/gameseditor/ui/scoreeditor/ScoreEditor.kt, android/feature/gearform/src/main/java/ca/josephroque/bowlingcompanion/feature/gearform/GearFormScreenUi.kt, android/feature/gearform/src/main/java/ca/josephroque/bowlingcompanion/feature/gearform/GearFormViewModel.kt, android/feature/gearlist/src/main/java/ca/josephroque/bowlingcompanion/feature/gearlist/GearListViewModel.kt, android/feature/laneform/src/main/java/ca/josephroque/bowlingcompanion/feature/laneform/LaneFormViewModel.kt, android/feature/leagueform/src/main/java/ca/josephroque/bowlingcompanion/feature/leagueform/LeagueFormScreenUi.kt, android/feature/leagueform/src/main/java/ca/josephroque/bowlingcompanion/feature/leagueform/LeagueFormViewModel.kt, android/feature/matchplayeditor/src/main/java/ca/josephroque/bowlingcompanion/feature/matchplayeditor/MatchPlayEditorViewModel.kt, android/feature/seriesform/src/main/java/ca/josephroque/bowlingcompanion/feature/seriesform/SeriesFormScreenUi.kt, android/feature/seriesform/src/main/java/ca/josephroque/bowlingcompanion/feature/seriesform/SeriesFormViewModel.kt, android/feature/settings/src/main/java/ca/josephroque/bowlingcompanion/feature/settings/SettingsViewModel.kt, android/feature/statisticsdetails/src/main/java/ca/josephroque/bowlingcompanion/feature/statisticsdetails/StatisticsDetailsViewModel.kt, android/feature/statisticswidget/src/main/java/ca/josephroque/bowlingcompanion/feature/statisticswidget/statisticpicker/StatisticPickerViewModel.kt
=> refactor(android): use MutableStateFlow.update where possible

ios/Approach.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/Approach/Package.swift, ios/Approach/Package.swift.toml
=> chore(ios): bump swift-composable-architecture to 1.6.0

ios/Approach/Sources/BowlersRepository/BowlersRepository+Live.swift, ios/Approach/Sources/DatabaseLibrary/Migrations/Migration20231220RenameLeagueNumberOfGames.swift, ios/Approach/Sources/DatabaseModelsLibrary/Game+Database.swift, ios/Approach/Sources/StatisticsLibrary/TrackableFilter.swift, ios/Approach/Sources/StatisticsModelsLibrary/Series+TrackableRelationships.swift, ios/Approach/Sources/StatisticsRepository/Extensions/TrackableFilter+Extensions.swift
=> fix(ios): show series stats for pre-bowl series by including excluded games

android/feature/alleyform/ui/src/main/java/ca/josephroque/bowlingcompanion/feature/alleyform/ui/AlleyFormTopBar.kt, android/feature/bowlerform/ui/src/main/java/ca/josephroque/bowlingcompanion/feature/bowlerform/ui/BowlerFormTopBar.kt, android/feature/gearform/ui/src/main/java/ca/josephroque/bowlingcompanion/feature/gearform/ui/GearFormTopBar.kt, android/feature/laneform/ui/src/main/java/ca/josephroque/bowlingcompanion/feature/laneform/ui/LaneFormTopBar.kt, android/feature/leagueform/ui/src/main/java/ca/josephroque/bowlingcompanion/feature/leagueform/ui/LeagueFormTopBar.kt, android/feature/matchplayeditor/ui/src/main/java/ca/josephroque/bowlingcompanion/feature/matchplayeditor/ui/MatchPlayEditorTopBar.kt, android/feature/resourcepicker/ui/src/main/java/ca/josephroque/bowlingcompanion/feature/resourcepicker/ui/ResourcePickerTopBar.kt, android/feature/seriesform/ui/src/main/java/ca/josephroque/bowlingcompanion/feature/seriesform/ui/SeriesFormTopBar.kt, android/feature/statisticswidget/ui/src/main/java/ca/josephroque/bowlingcompanion/feature/statisticswidget/ui/editor/StatisticsWidgetEditorTopBar.kt
=> fix(android): replace top bar clickable text with TextButton

android/core/model/src/main/java/ca/josephroque/bowlingcompanion/core/model/Frame.kt, android/core/statistics/src/main/java/ca/josephroque/bowlingcompanion/core/statistics/trackable/overall/TotalRollsStatistic.kt, ios/Approach/Sources/StatisticsLibrary/Models/Frame+TrackableEntry.swift, ios/Approach/Sources/StatisticsLibrary/Trackable/Overall/Statistics+TotalRolls.swift
=> Ensure totalRolls only counts valid rolls on the frame

android/feature/gameseditor/src/main/java/ca/josephroque/bowlingcompanion/feature/gameseditor/utils/FrameUtilities.kt, ios/Approach/Sources/DatabaseLibrary/Migrations/DBMigration.swift, ios/Approach/Sources/DatabaseLibrary/Migrations/Migration20240329ClearExtraRolledBalls.swift, ios/Approach/Sources/FramesRepositoryInterface/Models/Frame+Edit.swift, ios/Approach/Tests/DatabaseLibraryTests/DBMigrationTests.swift
=> Remove bowling balls from rolls after strikes and spares

android/app/src/main/java/ca/josephroque/bowlingcompanion/navigation/graph/AccessoriesGraph.kt, android/app/src/main/java/ca/josephroque/bowlingcompanion/navigation/graph/BottomSheetGraph.kt, android/core/data/src/main/java/ca/josephroque/bowlingcompanion/core/data/migration/SQLiteMigrationService.kt, android/core/data/src/main/java/ca/josephroque/bowlingcompanion/core/data/repository/BowlersRepository.kt, android/core/data/src/main/java/ca/josephroque/bowlingcompanion/core/data/repository/OfflineFirstBowlersRepository.kt, android/core/data/src/main/java/ca/josephroque/bowlingcompanion/core/data/repository/OfflineFirstStatisticsRepository.kt, android/core/database/src/main/java/ca/josephroque/bowlingcompanion/core/database/dao/AlleyDao.kt, android/core/database/src/main/java/ca/josephroque/bowlingcompanion/core/database/dao/BowlerDao.kt, android/core/database/src/main/java/ca/josephroque/bowlingcompanion/core/database/dao/GearDao.kt, android/core/database/src/main/java/ca/josephroque/bowlingcompanion/core/database/dao/LaneDao.kt, android/feature/overview/src/main/java/ca/josephroque/bowlingcompanion/feature/overview/OverviewViewModel.kt, android/feature/resourcepicker/src/main/java/ca/josephroque/bowlingcompanion/feature/resourcepicker/ResourcePickerViewModel.kt, android/feature/resourcepicker/src/main/java/ca/josephroque/bowlingcompanion/feature/resourcepicker/data/BowlerPickerDataProvider.kt, android/feature/resourcepicker/src/main/java/ca/josephroque/bowlingcompanion/feature/resourcepicker/navigation/ResourcePickerNavigation.kt, android/feature/resourcepicker/ui/src/main/java/ca/josephroque/bowlingcompanion/feature/resourcepicker/ui/ResourcePickerUi.kt
=> Show all bowlers + opponents in the opponent picker

android/core/featureflags/src/main/java/ca/josephroque/bowlingcompanion/core/featureflags/FeatureFlag.kt, android/core/navigation/src/main/java/ca/josephroque/bowlingcompanion/core/navigation/AvatarFormResultViewModel.kt, android/core/navigation/src/main/java/ca/josephroque/bowlingcompanion/core/navigation/GamesSettingsResultViewModel.kt, android/core/navigation/src/main/java/ca/josephroque/bowlingcompanion/core/navigation/LaneFormResultViewModel.kt, android/core/navigation/src/main/java/ca/josephroque/bowlingcompanion/core/navigation/ResourcePickerResultViewModel.kt, android/core/navigation/src/main/java/ca/josephroque/bowlingcompanion/core/navigation/ScoreEditorResultViewModel.kt, android/core/navigation/src/main/java/ca/josephroque/bowlingcompanion/core/navigation/SeriesFormResultViewModel.kt, android/core/navigation/src/main/java/ca/josephroque/bowlingcompanion/core/navigation/StatisticPickerResultViewModel.kt, android/feature/quickplay/src/main/java/ca/josephroque/bowlingcompanion/feature/quickplay/QuickPlayViewModel.kt
=> Set picker results to null instead of removing
